import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
  size = 12

  [font.normal]
    family = "JetBrainsMono Nerd Font"
    style = "Regular"

  [font.bold]
    family = "JetBrainsMono Nerd Font"
    style = "Bold"

  [font.italic]
    family = "JetBrainsMono Nerd Font"
    style = "Italic"
