{{- /* chezmoi:modify-template */ -}}
{{- $config := .chezmoi.stdin | fromToml -}}
{{- $config = setValueAtPath "tools.bun" "latest" $config -}}
{{- $config = setValueAtPath "tools.node" "lts" $config -}}
{{- $config = setValueAtPath "tools.uv" "latest" $config -}}
{{- $config | toToml -}}
